export const countries = [
  {label: 'Afghanistan', value: 'AF', icon: '/assets/icons/countries/AF.svg'},
  {label: 'Åland Islands', value: 'AX', icon: '/assets/icons/countries/AX.svg'},
  {label: 'Albania', value: 'AL', icon: '/assets/icons/countries/AL.svg'},
  {label: 'Algeria', value: 'DZ', icon: '/assets/icons/countries/DZ.svg'},
  {label: 'American Samoa', value: 'AS', icon: '/assets/icons/countries/AS.svg'},
  {label: 'AndorrA', value: 'AD', icon: '/assets/icons/countries/AD.svg'},
  {label: 'Angola', value: 'AO', icon: '/assets/icons/countries/AO.svg'},
  {label: 'Anguilla', value: 'AI', icon: '/assets/icons/countries/AI.svg'},
  {label: 'Antarctica', value: 'AQ', icon: '/assets/icons/countries/AQ.svg'},
  {label: 'Antigua and Barbuda', value: 'AG', icon: '/assets/icons/countries/AG.svg'},
  {label: 'Argentina', value: 'AR', icon: '/assets/icons/countries/AR.svg'},
  {label: 'Armenia', value: 'AM', icon: '/assets/icons/countries/AM.svg'},
  {label: 'Aruba', value: 'AW', icon: '/assets/icons/countries/AW.svg'},
  {label: 'Australia', value: 'AU', icon: '/assets/icons/countries/AU.svg'},
  {label: 'Austria', value: 'AT', icon: '/assets/icons/countries/AT.svg'},
  {label: 'Azerbaijan', value: 'AZ', icon: '/assets/icons/countries/AZ.svg'},
  {label: 'Bahamas', value: 'BS', icon: '/assets/icons/countries/BS.svg'},
  {label: 'Bahrain', value: 'BH', icon: '/assets/icons/countries/BH.svg'},
  {label: 'Bangladesh', value: 'BD', icon: '/assets/icons/countries/BD.svg'},
  {label: 'Barbados', value: 'BB', icon: '/assets/icons/countries/BB.svg'},
  {label: 'Belarus', value: 'BY', icon: '/assets/icons/countries/BY.svg'},
  {label: 'Belgium', value: 'BE', icon: '/assets/icons/countries/BE.svg'},
  {label: 'Belize', value: 'BZ', icon: '/assets/icons/countries/BZ.svg'},
  {label: 'Benin', value: 'BJ', icon: '/assets/icons/countries/BJ.svg'},
  {label: 'Bermuda', value: 'BM', icon: '/assets/icons/countries/BM.svg'},
  {label: 'Bhutan', value: 'BT', icon: '/assets/icons/countries/BT.svg'},
  {label: 'Bolivia', value: 'BO', icon: '/assets/icons/countries/BO.svg'},
  {label: 'Bosnia and Herzegovina', value: 'BA', icon: '/assets/icons/countries/BA.svg'},
  {label: 'Botswana', value: 'BW', icon: '/assets/icons/countries/BW.svg'},
  {label: 'Bouvet Island', value: 'BV', icon: '/assets/icons/countries/BV.svg'},
  {label: 'Brazil', value: 'BR', icon: '/assets/icons/countries/BR.svg'},
  {label: 'British Indian Ocean Territory', value: 'IO', icon: '/assets/icons/countries/IO.svg'},
  {label: 'Brunei Darussalam', value: 'BN', icon: '/assets/icons/countries/BN.svg'},
  {label: 'Bulgaria', value: 'BG', icon: '/assets/icons/countries/BG.svg'},
  {label: 'Burkina Faso', value: 'BF', icon: '/assets/icons/countries/BF.svg'},
  {label: 'Burundi', value: 'BI', icon: '/assets/icons/countries/BI.svg'},
  {label: 'Cambodia', value: 'KH', icon: '/assets/icons/countries/KH.svg'},
  {label: 'Cameroon', value: 'CM', icon: '/assets/icons/countries/CM.svg'},
  {label: 'Canada', value: 'CA', icon: '/assets/icons/countries/CA.svg'},
  {label: 'Cayman Islands', value: 'KY', icon: '/assets/icons/countries/KY.svg'},
  {label: 'Central African Republic', value: 'CF', icon: '/assets/icons/countries/CF.svg'},
  {label: 'Chad', value: 'TD', icon: '/assets/icons/countries/TD.svg'},
  {label: 'Chile', value: 'CL', icon: '/assets/icons/countries/CL.svg'},
  {label: 'China', value: 'CN', icon: '/assets/icons/countries/CN.svg'},
  {label: 'Christmas Island', value: 'CX', icon: '/assets/icons/countries/CX.svg'},
  {label: 'Cocos (Keeling) Islands', value: 'CC', icon: '/assets/icons/countries/CC.svg'},
  {label: 'Colombia', value: 'CO', icon: '/assets/icons/countries/CO.svg'},
  {label: 'Comoros', value: 'KM', icon: '/assets/icons/countries/KM.svg'},
  {label: 'Congo', value: 'CG', icon: '/assets/icons/countries/CG.svg'},
  {label: 'Congo, The Democratic Republic of the', value: 'CD', icon: '/assets/icons/countries/CD.svg'},
  {label: 'Cook Islands', value: 'CK', icon: '/assets/icons/countries/CK.svg'},
  {label: 'Costa Rica', value: 'CR', icon: '/assets/icons/countries/CR.svg'},
  {label: 'Cote D\'Ivoire', value: 'CI', icon: '/assets/icons/countries/CI.svg'},
  {label: 'Croatia', value: 'HR', icon: '/assets/icons/countries/HR.svg'},
  {label: 'Cuba', value: 'CU', icon: '/assets/icons/countries/CU.svg'},
  {label: 'Curaçao', value: 'CW', icon: '/assets/icons/countries/CU.svg'},
  {label: 'Cyprus', value: 'CY', icon: '/assets/icons/countries/CY.svg'},
  {label: 'Czech Republic', value: 'CZ', icon: '/assets/icons/countries/CZ.svg'},
  {label: 'Denmark', value: 'DK', icon: '/assets/icons/countries/DK.svg'},
  {label: 'Djibouti', value: 'DJ', icon: '/assets/icons/countries/DJ.svg'},
  {label: 'Dominica', value: 'DM', icon: '/assets/icons/countries/DM.svg'},
  {label: 'Dominican Republic', value: 'DO', icon: '/assets/icons/countries/DO.svg'},
  {label: 'Ecuador', value: 'EC', icon: '/assets/icons/countries/EC.svg'},
  {label: 'Egypt', value: 'EG', icon: '/assets/icons/countries/EG.svg'},
  {label: 'El Salvador', value: 'SV', icon: '/assets/icons/countries/SV.svg'},
  {label: 'Equatorial Guinea', value: 'GQ', icon: '/assets/icons/countries/GQ.svg'},
  {label: 'Eritrea', value: 'ER', icon: '/assets/icons/countries/ER.svg'},
  {label: 'Estonia', value: 'EE', icon: '/assets/icons/countries/EE.svg'},
  {label: 'Ethiopia', value: 'ET', icon: '/assets/icons/countries/ET.svg'},
  {label: 'Falkland Islands (Malvinas)', value: 'FK', icon: '/assets/icons/countries/FK.svg'},
  {label: 'Faroe Islands', value: 'FO', icon: '/assets/icons/countries/FO.svg'},
  {label: 'Fiji', value: 'FJ', icon: '/assets/icons/countries/FJ.svg'},
  {label: 'Finland', value: 'FI', icon: '/assets/icons/countries/FI.svg'},
  {label: 'France', value: 'FR', icon: '/assets/icons/countries/FR.svg'},
  {label: 'French Guiana', value: 'GF', icon: '/assets/icons/countries/GF.svg'},
  {label: 'French Polynesia', value: 'PF', icon: '/assets/icons/countries/PF.svg'},
  {label: 'French Southern Territories', value: 'TF', icon: '/assets/icons/countries/TF.svg'},
  {label: 'Gabon', value: 'GA', icon: '/assets/icons/countries/GA.svg'},
  {label: 'Gambia', value: 'GM', icon: '/assets/icons/countries/GM.svg'},
  {label: 'Georgia', value: 'GE', icon: '/assets/icons/countries/GE.svg'},
  {label: 'Germany', value: 'DE', icon: '/assets/icons/countries/DE.svg'},
  {label: 'Ghana', value: 'GH', icon: '/assets/icons/countries/GH.svg'},
  {label: 'Gibraltar', value: 'GI', icon: '/assets/icons/countries/GI.svg'},
  {label: 'Greece', value: 'GR', icon: '/assets/icons/countries/GR.svg'},
  {label: 'Greenland', value: 'GL', icon: '/assets/icons/countries/GL.svg'},
  {label: 'Grenada', value: 'GD', icon: '/assets/icons/countries/GD.svg'},
  {label: 'Guadeloupe', value: 'GP', icon: '/assets/icons/countries/GP.svg'},
  {label: 'Guam', value: 'GU', icon: '/assets/icons/countries/GU.svg'},
  {label: 'Guatemala', value: 'GT', icon: '/assets/icons/countries/GT.svg'},
  {label: 'Guernsey', value: 'GG', icon: '/assets/icons/countries/GG.svg'},
  {label: 'Guinea', value: 'GN', icon: '/assets/icons/countries/GN.svg'},
  {label: 'Guinea-Bissau', value: 'GW', icon: '/assets/icons/countries/GW.svg'},
  {label: 'Guyana', value: 'GY', icon: '/assets/icons/countries/GY.svg'},
  {label: 'Haiti', value: 'HT', icon: '/assets/icons/countries/HT.svg'},
  {label: 'Heard Island and Mcdonald Islands', value: 'HM', icon: '/assets/icons/countries/HM.svg'},
  {label: 'Holy See (Vatican City State)', value: 'VA', icon: '/assets/icons/countries/VA.svg'},
  {label: 'Honduras', value: 'HN', icon: '/assets/icons/countries/HN.svg'},
  {label: 'Hong Kong', value: 'HK', icon: '/assets/icons/countries/HK.svg'},
  {label: 'Hungary', value: 'HU', icon: '/assets/icons/countries/HU.svg'},
  {label: 'Iceland', value: 'IS', icon: '/assets/icons/countries/IS.svg'},
  {label: 'India', value: 'IN', icon: '/assets/icons/countries/IN.svg'},
  {label: 'Indonesia', value: 'ID', icon: '/assets/icons/countries/ID.svg'},
  {label: 'Iran, Islamic Republic Of', value: 'IR', icon: '/assets/icons/countries/IR.svg'},
  {label: 'Iraq', value: 'IQ', icon: '/assets/icons/countries/IQ.svg'},
  {label: 'Ireland', value: 'IE', icon: '/assets/icons/countries/IE.svg'},
  {label: 'Isle of Man', value: 'IM', icon: '/assets/icons/countries/IM.svg'},
  {label: 'Israel', value: 'IL', icon: '/assets/icons/countries/IL.svg'},
  {label: 'Italy', value: 'IT', icon: '/assets/icons/countries/IT.svg'},
  {label: 'Jamaica', value: 'JM', icon: '/assets/icons/countries/JM.svg'},
  {label: 'Japan', value: 'JP', icon: '/assets/icons/countries/JP.svg'},
  {label: 'Jersey', value: 'JE', icon: '/assets/icons/countries/JE.svg'},
  {label: 'Jordan', value: 'JO', icon: '/assets/icons/countries/JO.svg'},
  {label: 'Kazakhstan', value: 'KZ', icon: '/assets/icons/countries/KZ.svg'},
  {label: 'Kenya', value: 'KE', icon: '/assets/icons/countries/KE.svg'},
  {label: 'Kiribati', value: 'KI', icon: '/assets/icons/countries/KI.svg'},
  {label: 'Korea, Democratic People\'S Republic of', value: 'KP', icon: '/assets/icons/countries/KP.svg'},
  {label: 'Korea, Republic of', value: 'KR', icon: '/assets/icons/countries/KR.svg'},
  {label: 'Kuwait', value: 'KW', icon: '/assets/icons/countries/KW.svg'},
  {label: 'Kyrgyzstan', value: 'KG', icon: '/assets/icons/countries/KG.svg'},
  {label: 'Lao People\'S Democratic Republic', value: 'LA', icon: '/assets/icons/countries/LA.svg'},
  {label: 'Latvia', value: 'LV', icon: '/assets/icons/countries/LV.svg'},
  {label: 'Lebanon', value: 'LB', icon: '/assets/icons/countries/LB.svg'},
  {label: 'Lesotho', value: 'LS', icon: '/assets/icons/countries/LS.svg'},
  {label: 'Liberia', value: 'LR', icon: '/assets/icons/countries/LR.svg'},
  {label: 'Libyan Arab Jamahiriya', value: 'LY', icon: '/assets/icons/countries/LY.svg'},
  {label: 'Liechtenstein', value: 'LI', icon: '/assets/icons/countries/LI.svg'},
  {label: 'Lithuania', value: 'LT', icon: '/assets/icons/countries/LT.svg'},
  {label: 'Luxembourg', value: 'LU', icon: '/assets/icons/countries/LU.svg'},
  {label: 'Macao', value: 'MO', icon: '/assets/icons/countries/MO.svg'},
  {label: 'Macedonia, The Former Yugoslav Republic of', value: 'MK', icon: '/assets/icons/countries/MK.svg'},
  {label: 'Madagascar', value: 'MG', icon: '/assets/icons/countries/MG.svg'},
  {label: 'Malawi', value: 'MW', icon: '/assets/icons/countries/MW.svg'},
  {label: 'Malaysia', value: 'MY', icon: '/assets/icons/countries/MY.svg'},
  {label: 'Maldives', value: 'MV', icon: '/assets/icons/countries/MV.svg'},
  {label: 'Mali', value: 'ML', icon: '/assets/icons/countries/ML.svg'},
  {label: 'Malta', value: 'MT', icon: '/assets/icons/countries/MT.svg'},
  {label: 'Marshall Islands', value: 'MH', icon: '/assets/icons/countries/MH.svg'},
  {label: 'Martinique', value: 'MQ', icon: '/assets/icons/countries/MQ.svg'},
  {label: 'Mauritania', value: 'MR', icon: '/assets/icons/countries/MR.svg'},
  {label: 'Mauritius', value: 'MU', icon: '/assets/icons/countries/MU.svg'},
  {label: 'Mayotte', value: 'YT', icon: '/assets/icons/countries/YT.svg'},
  {label: 'Mexico', value: 'MX', icon: '/assets/icons/countries/MX.svg'},
  {label: 'Micronesia, Federated States of', value: 'FM', icon: '/assets/icons/countries/FM.svg'},
  {label: 'Moldova, Republic of', value: 'MD', icon: '/assets/icons/countries/MD.svg'},
  {label: 'Montenegro', value: 'ME', icon: '/assets/icons/countries/ME.svg'},
  {label: 'Monaco', value: 'MC', icon: '/assets/icons/countries/MC.svg'},
  {label: 'Mongolia', value: 'MN', icon: '/assets/icons/countries/MN.svg'},
  {label: 'Montserrat', value: 'MS', icon: '/assets/icons/countries/MS.svg'},
  {label: 'Morocco', value: 'MA', icon: '/assets/icons/countries/MA.svg'},
  {label: 'Mozambique', value: 'MZ', icon: '/assets/icons/countries/MZ.svg'},
  {label: 'Myanmar', value: 'MM', icon: '/assets/icons/countries/MM.svg'},
  {label: 'Namibia', value: 'NA', icon: '/assets/icons/countries/NA.svg'},
  {label: 'Nauru', value: 'NR', icon: '/assets/icons/countries/NR.svg'},
  {label: 'Nepal', value: 'NP', icon: '/assets/icons/countries/NP.svg'},
  {label: 'Netherlands', value: 'NL', icon: '/assets/icons/countries/NL.svg'},
  {label: 'New Zealand', value: 'NZ', icon: '/assets/icons/countries/NZ.svg'},
  {label: 'Nicaragua', value: 'NI', icon: '/assets/icons/countries/NI.svg'},
  {label: 'Niger', value: 'NE', icon: '/assets/icons/countries/NE.svg'},
  {label: 'Nigeria', value: 'NG', icon: '/assets/icons/countries/NG.svg'},
  {label: 'Niue', value: 'NU', icon: '/assets/icons/countries/NU.svg'},
  {label: 'Norfolk Island', value: 'NF', icon: '/assets/icons/countries/NF.svg'},
  {label: 'Northern Mariana Islands', value: 'MP', icon: '/assets/icons/countries/MP.svg'},
  {label: 'Norway', value: 'NO', icon: '/assets/icons/countries/NO.svg'},
  {label: 'Oman', value: 'OM', icon: '/assets/icons/countries/OM.svg'},
  {label: 'Pakistan', value: 'PK', icon: '/assets/icons/countries/PK.svg'},
  {label: 'Palau', value: 'PW', icon: '/assets/icons/countries/PW.svg'},
  {label: 'Palestinian Territory, Occupied', value: 'PS', icon: '/assets/icons/countries/PS.svg'},
  {label: 'Panama', value: 'PA', icon: '/assets/icons/countries/PA.svg'},
  {label: 'Papua New Guinea', value: 'PG', icon: '/assets/icons/countries/PG.svg'},
  {label: 'Paraguay', value: 'PY', icon: '/assets/icons/countries/PY.svg'},
  {label: 'Peru', value: 'PE', icon: '/assets/icons/countries/PE.svg'},
  {label: 'Philippines', value: 'PH', icon: '/assets/icons/countries/PH.svg'},
  {label: 'Pitcairn', value: 'PN', icon: '/assets/icons/countries/PN.svg'},
  {label: 'Poland', value: 'PL', icon: '/assets/icons/countries/PL.svg'},
  {label: 'Portugal', value: 'PT', icon: '/assets/icons/countries/PT.svg'},
  {label: 'Puerto Rico', value: 'PR', icon: '/assets/icons/countries/PR.svg'},
  {label: 'Qatar', value: 'QA', icon: '/assets/icons/countries/QA.svg'},
  {label: 'Romania', value: 'RO', icon: '/assets/icons/countries/RO.svg'},
  {label: 'Russia', value: 'RU', icon: '/assets/icons/countries/RU.svg'},
  {label: 'RWANDA', value: 'RW', icon: '/assets/icons/countries/RW.svg'},
  {label: 'Saint Helena', value: 'SH', icon: '/assets/icons/countries/SH.svg'},
  {label: 'Saint Kitts and Nevis', value: 'KN', icon: '/assets/icons/countries/KN.svg'},
  {label: 'Saint Lucia', value: 'LC', icon: '/assets/icons/countries/LC.svg'},
  {label: 'Saint Vincent and the Grenadines', value: 'VC', icon: '/assets/icons/countries/VC.svg'},
  {label: 'Samoa', value: 'WS', icon: '/assets/icons/countries/WS.svg'},
  {label: 'San Marino', value: 'SM', icon: '/assets/icons/countries/SM.svg'},
  {label: 'Sao Tome and Principe', value: 'ST', icon: '/assets/icons/countries/ST.svg'},
  {label: 'Saudi Arabia', value: 'SA', icon: '/assets/icons/countries/SA.svg'},
  {label: 'Senegal', value: 'SN', icon: '/assets/icons/countries/SN.svg'},
  {label: 'Serbia', value: 'CS', icon: '/assets/icons/countries/CS.svg'},
  {label: 'Seychelles', value: 'SC', icon: '/assets/icons/countries/SC.svg'},
  {label: 'Sierra Leone', value: 'SL', icon: '/assets/icons/countries/SL.svg'},
  {label: 'Singapore', value: 'SG', icon: '/assets/icons/countries/SG.svg'},
  {label: 'Sint Maarten (Dutch part)', value: 'SX', icon: '/assets/icons/countries/SX.svg'},
  {label: 'Slovakia', value: 'SK', icon: '/assets/icons/countries/SK.svg'},
  {label: 'Slovenia', value: 'SI', icon: '/assets/icons/countries/SI.svg'},
  {label: 'Solomon Islands', value: 'SB', icon: '/assets/icons/countries/SB.svg'},
  {label: 'Somalia', value: 'SO', icon: '/assets/icons/countries/SO.svg'},
  {label: 'South Africa', value: 'ZA', icon: '/assets/icons/countries/ZA.svg'},
  {label: 'South Georgia and the South Sandwich Islands', value: 'GS', icon: '/assets/icons/countries/GS.svg'},
  {label: 'Spain', value: 'ES', icon: '/assets/icons/countries/ES.svg'},
  {label: 'Sri Lanka', value: 'LK', icon: '/assets/icons/countries/LK.svg'},
  {label: 'Sudan', value: 'SD', icon: '/assets/icons/countries/SD.svg'},
  {label: 'Suriname', value: 'SR', icon: '/assets/icons/countries/SR.svg'},
  {label: 'Svalbard and Jan Mayen', value: 'SJ', icon: '/assets/icons/countries/SJ.svg'},
  {label: 'Swaziland', value: 'SZ', icon: '/assets/icons/countries/SZ.svg'},
  {label: 'Sweden', value: 'SE', icon: '/assets/icons/countries/SE.svg'},
  {label: 'Switzerland', value: 'CH', icon: '/assets/icons/countries/CH.svg'},
  {label: 'Syrian Arab Republic', value: 'SY', icon: '/assets/icons/countries/SY.svg'},
  {label: 'Taiwan, Province of China', value: 'TW', icon: '/assets/icons/countries/TW.svg'},
  {label: 'Tajikistan', value: 'TJ', icon: '/assets/icons/countries/TJ.svg'},
  {label: 'Tanzania, United Republic of', value: 'TZ', icon: '/assets/icons/countries/TZ.svg'},
  {label: 'Thailand', value: 'TH', icon: '/assets/icons/countries/TH.svg'},
  {label: 'Timor-Leste', value: 'TL', icon: '/assets/icons/countries/TL.svg'},
  {label: 'Togo', value: 'TG', icon: '/assets/icons/countries/TG.svg'},
  {label: 'Tokelau', value: 'TK', icon: '/assets/icons/countries/TK.svg'},
  {label: 'Tonga', value: 'TO', icon: '/assets/icons/countries/TO.svg'},
  {label: 'Trinidad and Tobago', value: 'TT', icon: '/assets/icons/countries/TT.svg'},
  {label: 'Tunisia', value: 'TN', icon: '/assets/icons/countries/TN.svg'},
  {label: 'Turkey', value: 'TR', icon: '/assets/icons/countries/TR.svg'},
  {label: 'Turkmenistan', value: 'TM', icon: '/assets/icons/countries/TM.svg'},
  {label: 'Turks and Caicos Islands', value: 'TC', icon: '/assets/icons/countries/TC.svg'},
  {label: 'Tuvalu', value: 'TV', icon: '/assets/icons/countries/TV.svg'},
  {label: 'Uganda', value: 'UG', icon: '/assets/icons/countries/UG.svg'},
  {label: 'Ukraine', value: 'UA', icon: '/assets/icons/countries/UA.svg'},
  {label: 'United Arab Emirates', value: 'AE', icon: '/assets/icons/countries/AE.svg'},
  {label: 'United Kingdom', value: 'GB', icon: '/assets/icons/countries/GB.svg'},
  {label: 'United States', value: 'US', icon: '/assets/icons/countries/US.svg'},
  {label: 'United States Minor Outlying Islands', value: 'UM', icon: '/assets/icons/countries/UM.svg'},
  {label: 'Uruguay', value: 'UY', icon: '/assets/icons/countries/UY.svg'},
  {label: 'Uzbekistan', value: 'UZ', icon: '/assets/icons/countries/UZ.svg'},
  {label: 'Vanuatu', value: 'VU', icon: '/assets/icons/countries/VU.svg'},
  {label: 'Venezuela', value: 'VE', icon: '/assets/icons/countries/VE.svg'},
  {label: 'Viet Nam', value: 'VN', icon: '/assets/icons/countries/VN.svg'},
  {label: 'Virgin Islands, British', value: 'VG', icon: '/assets/icons/countries/VG.svg'},
  {label: 'Virgin Islands, U.S.', value: 'VI', icon: '/assets/icons/countries/VI.svg'},
  {label: 'Wallis and Futuna', value: 'WF', icon: '/assets/icons/countries/WF.svg'},
  {label: 'Western Sahara', value: 'EH', icon: '/assets/icons/countries/EH.svg'},
  {label: 'Yemen', value: 'YE', icon: '/assets/icons/countries/YE.svg'},
  {label: 'Zambia', value: 'ZM', icon: '/assets/icons/countries/ZM.svg'},
  {label: 'Zimbabwe', value: 'ZW',icon: '/assets/icons/countries/ZW.svg'},
 ];
 